### ISSUE TITLE
Ziggy does not kill processes properly

### ISSUE THREAD

**Issue by brunoproduit** [srlabs/ziggy#16]
When running fuzzers with ziggy, sometimes subprocesses do not get killed properly when stopping ziggy.

Ziggy should gracefully handle stopping by catching the CTRL-C, waiting for subprocesses to be stopped properly and only then stop itself

**Comment by louismerlin** [comment]
Fixed in https://github.com/srlabs/ziggy/commit/057ab8530907c84ecc503c3a5287a84e4817b7ae.
