### ISSUE TITLE
Add QEMU mode for some AFL++ secondary fuzzers

### ISSUE THREAD

**Issue by louismerlin** [srlabs/ziggy#30]
QEMU mode (`-Q`) could be used for certain secondary fuzzers.

**Comment by vanhauser-thc** [comment]
I tried it, it does not much sense because of the huge targets. also tried with frida etc.
it is just very slow, difficult coverage gathering.
I recommend closing this.

**Comment by louismerlin** [comment]
Yep this was our feeling too. Thank you for checking it out.
